### PR TITLE
Better File Browser names

### LINKED ISSUE #39: Enhance `File Browser` in tinfoil to display more information
File browser actually display `[gameId][version].nsp`, it could be nice to have more information.

To enhance this, we should modify the `AddNewGames` function (in `gamescollection/collection.go`) to add more information after the `#` sign.

Some information, like name, region and maybe release date could be useful.

### PR DESCRIPTION
**Pull request by Helvio88**
Should fix #39 by showing actual file name

### CODE REVIEW

**Comment by DblK** [comment]
This can't work. The name of the original file can be malformed or with additional information that we do not want to be in the listing in `tinfoil`.

I would suggest to ensure with `HasGameIDInLibrary` that the gameId is in the library and use `c.Library()[file.GameID]` (type `TitleDBEntry`) as base of information. Using properties `Name`, `Region` and the actual code `file.GameInfo`.

This will ensure we will have the same format as output in the listing.
You can test it by adding an empty file for example named `[0100CC00102B4000][v0].nsp` in your `games` folder.

If you use the browser you should see the label `Tony Hawk's™ Pro Skater™ 1 + 2` if you don't then the feature is not complete and can not be merged.

As suggested, we can thing about something like this `Tony Hawk's™ Pro Skater™ 1 + 2 (EN)[0100CC00102B4000][v0].nsp` to be displayed.

I hope I am clear enough for the change to be made.

**Comment by Helvio88** [comment]
I believe I pulled it off! Added a function to convert ID to Base ID in case it's an Update or DLC ID.
A combination of Title ID and Base ID allows for proper entry naming. Works on my test cases!

Perhaps some best practices could be implemented on my code, please forgive my amateur skills. But, it works!

**Comment by DblK** [comment]
Thx, I will have a look and once tested will come back to you.

**Comment by DblK** [comment]
I reviewed and make some changes

**Pull request merged**
